// Static SEO metadata for popular items, bundled at build time from the
// Tibia API. Generated by scripts/fetch-item-metadata.js — re-run that
// script when POPULAR_ITEMS changes.
//
// Each entry powers the per-item SSR body content rendered by SEOContent —
// category, NPC offers and same-category cross-links — so every prerendered
// item page gets unique, crawlable text instead of the boilerplate that
// triggered Google's "URL is unknown" verdict for all 150 item URLs.

import metadata from './itemSeoMetadata.json';

export interface NpcOffer {
  name: string;
  location: string;
  price: number;
}

export interface ItemSeoMetadata {
  id: number;
  category: string;
  wiki_name: string;
  npc_sell: NpcOffer[];
  npc_buy: NpcOffer[];
}

const META = metadata as Record<string, ItemSeoMetadata>;

export function getItemSeoMetadata(name: string): ItemSeoMetadata | null {
  return META[name] ?? null;
}

// Returns up to `limit` item names from the same category, excluding the
// item itself. Sorted alphabetically for stable output across builds.
export function getRelatedItemNames(name: string, limit = 8): string[] {
  const meta = META[name];
  if (!meta) return [];
  return Object.entries(META)
    .filter(([n, m]) => n !== name && m.category === meta.category)
    .map(([n]) => n)
    .sort()
    .slice(0, limit);
}
